In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Ler o Csv e mostrar as primeiras 5 linhas
df = pd.read_csv("JogosMetacriticCompleto.csv", delimiter = ";")
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24342 entries, 0 to 24341
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Link              16051 non-null  object
 1   Nome              24342 non-null  object
 2   NotaCritico       16967 non-null  float64
 3   NumCritics        16910 non-null  float64
 4   NotaPublico       17011 non-null  float64
 5   NumPublicCritics  16831 non-null  float64
 6   NA_Sales          15811 non-null  float64
 7   EU_Sales          15811 non-null  float64
 8   JP_Sales          15811 non-null  float64
 9   Other_Sales       15811 non-null  float64
 10  Global_Sales      15827 non-null  float64
 11  DataLancamento    24214 non-null  object
 12  Plataforma        24342 non-null  object
 13  ImagemUrl         16051 non-null  object
 14  Summary           15988 non-null  object
 15  Developer         18412 non-null  object
 16  Publisher         16014 non-null  object
 17  Genre             24342 non-null  object
 18  GenreMetacritic   15988 non-null  object
 19  NoOfPlayers       8125 non-null   object
 20  Rate              14508 non-null  object
 21  AnoLancamento     24214 non-null  float64
dtypes: float64(10), object(12)
memory usage: 4.1+ MB
None

,Link,Nome,NotaCritico,NumCritics,NotaPublico,NumPublicCritics,NA_Sales,EU_Sales,JP_Sales,Other_Sales,...,Plataforma,ImagemUrl,Summary,Developer,Publisher,Genre,GenreMetacritic,NoOfPlayers,Rate,AnoLancamento
0,/game/nintendo-64/the-legend-of-zelda-ocarina-...,The Legend of Zelda: Ocarina of Time,99.0,22.0,9.1,4673.0,2.09,1.31,0.62,0.31,...,Nintendo 64,https://static.metacritic.com/images/products/...,"As a young boy, Link is tricked by Ganondorf, ...",Nintendo,Nintendo,Action,"Action Adventure, Fantasy",1 Player,E,1998.0
1,/game/playstation/tony-hawks-pro-skater-2,Tony Hawk's Pro Skater 2,98.0,19.0,7.5,494.0,3.05,1.41,0.02,0.20,...,Playstation,https://static.metacritic.com/images/products/...,The BEST SKATEBOARDING GAME.YEEEEEEEEEEEEEEEEE...,Neversoft Entertainment,Activision,Sports,"Sports, Alternative, Skateboarding",NaN,T,2000.0
2,/game/playstation-3/grand-theft-auto-iv,Grand Theft Auto IV,98.0,64.0,7.5,3291.0,4.76,3.69,0.44,1.61,...,Playstation 3,https://static.metacritic.com/images/products/...,[Metacritic's 2008 PS3 Game of the Year; Also ...,Rockstar North,Take-Two Interactive,Action,"Action Adventure, Modern, Modern, Open-World",1 Player,M,2008.0
3,/game/dreamcast/soulcalibur,SoulCalibur,98.0,24.0,8.6,271.0,0.00,0.00,0.34,0.00,...,Dreamcast,https://static.metacritic.com/images/products/...,It&#039;s Soul Caliber. Tekken is poor compar...,Namco,Namco Bandai Games,Fighting,"Action, Fighting, 3D",NaN,T,1999.0
4,/game/xbox-360/grand-theft-auto-iv,Grand Theft Auto IV,98.0,86.0,7.9,3182.0,6.76,3.07,0.14,1.03,...,Xbox 360,https://static.metacritic.com/images/products/...,[Metacritic's 2008 Xbox 360 Game of the Year; ...,Rockstar North,Take-Two Interactive,Action,"Action Adventure, Modern, Modern, Open-World",1 Player,M,2008.0

In [3]:
df=df[['Nome','NotaCritico','NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales',
       'AnoLancamento','Plataforma','Publisher','Developer','Genre']]

In [4]:
df.dropna(inplace=True)

# Completar as colunas com desconhecido
cols = ['Developer', 'Publisher']
for col in cols:
    df[col].fillna('Unknown', inplace=True)

#Completa o ano de lanÃ§amento colocando a mÃ©dia dos jogos da plataforma
df['AnoLancamento'] = df.groupby("Plataforma")['AnoLancamento'].transform(lambda x: x.fillna(x.mean()))

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8305 entries, 0 to 24334
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome           8305 non-null   object
 1   NotaCritico    8305 non-null   float64
 2   NA_Sales       8305 non-null   float64
 3   EU_Sales       8305 non-null   float64
 4   JP_Sales       8305 non-null   float64
 5   Other_Sales    8305 non-null   float64
 6   Global_Sales   8305 non-null   float64
 7   AnoLancamento  8305 non-null   float64
 8   Plataforma     8305 non-null   object
 9   Publisher      8305 non-null   object
 10  Developer      8305 non-null   object
 11  Genre          8305 non-null   object
dtypes: float64(7), object(5)
memory usage: 843.5+ KB
None

In [12]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

def test_classifier(clf, df,params):
    X = df[params].values
    y = df['Hit']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
    clf = clf.fit(X_train, y_train)
    print('Accuracy: ', accuracy_score(clf.predict(X_test), y_test))
    print('Precision: ', precision_score(clf.predict(X_test), y_test, average="macro"))
    print('Recall: ', recall_score(clf.predict(X_test), y_test, average="macro"))
    print('F1: ', f1_score(clf.predict(X_test), y_test, average="macro"))
    print(confusion_matrix(y_test, clf.predict(X_test)))

In [13]:
from pandas import get_dummies
df2 = df[['Plataforma','Genre','Publisher','AnoLancamento','NotaCritico']]
df_copy = pd.get_dummies(df2)

In [14]:
df_copy.head()

,AnoLancamento,NotaCritico,Plataforma_3DS,Plataforma_DC,Plataforma_DS,Plataforma_Dreamcast,Plataforma_Game Boy Advance,Plataforma_Game Cube,Plataforma_Nintendo 64,Plataforma_PC,...,Publisher_Xicat Interactive,Publisher_Xplosiv,Publisher_Xseed Games,Publisher_Yacht Club Games,Publisher_Yeti,Publisher_Yuke's,Publisher_Zoo Digital Publishing,Publisher_Zoo Games,Publisher_Zushi Games,Publisher_bitComposer Games
0,1998.0,99.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2000.0,98.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2008.0,98.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1999.0,98.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2008.0,98.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df3 = df_copy
df3=df3.dropna(axis=1,how='all')

y = df3['NotaCritico'].values
df3 = df3.drop(['NotaCritico'],axis=1)
X = df3.values

In [16]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.50, random_state=0)

In [17]:
regressor = LinearRegression()  
regressor.fit(Xtrain, ytrain)
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

-27312425072.93451
[-4.35760626e-02  1.44077007e+10  1.44077008e+10  1.44077007e+10
  1.44077007e+10  1.44077007e+10  1.44077007e+10  1.44077007e+10
  1.44077007e+10  1.44077007e+10  1.44077007e+10  1.44077007e+10
  1.44077007e+10  1.44077007e+10  1.44077007e+10  1.44077007e+10
  1.44077007e+10  1.44077007e+10  1.44077007e+10  1.44077007e+10
  1.44077007e+10  1.44077007e+10  4.21722146e+09  4.21722146e+09
  4.21722146e+09  4.21722146e+09  4.21722147e+09  4.21722147e+09
  4.21722147e+09  4.21722147e+09  4.21722147e+09  4.21722146e+09
  4.21722147e+09  4.21722147e+09  5.12596664e+10 -1.59358798e+11
 -2.27166984e+11  8.68750302e+09  8.68750303e+09  8.68750303e+09
  8.68750305e+09  8.68750304e+09  8.68750303e+09  8.68750302e+09
  8.68750303e+09 -8.19927074e+10  8.68750301e+09  2.33282238e+11
 -1.77094499e+11  8.68750304e+09  8.68750302e+09  8.68750302e+09
  8.68750303e+09  8.68750304e+09  8.68750303e+09  8.68750304e+09
  8.68750303e+09  5.28651526e+10 -4.44583919e+10  8.68750302e+09
  8.68750302e+09  8.68750303e+09  8.68750304e+09  8.68750302e+09
  8.68750302e+09  8.68750302e+09  8.68750303e+09  8.68750304e+09
 -4.81693071e+09  8.68750300e+09  8.68750302e+09  8.68750302e+09
  8.68750305e+09  8.68750303e+09  8.68750302e+09  8.68750303e+09
  8.68750302e+09  8.68750303e+09  8.68750304e+09  8.68750302e+09
  5.42831086e+09  8.68750303e+09 -1.57022803e+10  8.68750301e+09
  8.68750301e+09  8.68750302e+09  8.68750303e+09  2.79168872e+10
  8.68750302e+09  8.68750303e+09  8.68750302e+09  8.68750302e+09
  8.68750304e+09  8.68750304e+09  8.68750302e+09  8.68750304e+09
  8.68750302e+09  8.68750304e+09  8.68750303e+09  8.68750302e+09
  8.68750303e+09  8.68750305e+09  8.68750303e+09  8.68750304e+09
  8.68750303e+09  2.19919030e+09  8.68750304e+09  8.68750302e+09
  8.68750303e+09  8.68750301e+09  8.68750301e+09  8.68750303e+09
  1.44311271e+09  8.68750302e+09  2.78610819e+10  8.68750302e+09
  8.68750302e+09  8.68750303e+09  6.69410613e+09  8.68750304e+09
  8.68750303e+09  8.68750302e+09  8.68750304e+09  8.68750304e+09
  8.68750301e+09  8.68750304e+09  6.16076613e+09  8.68750302e+09
 -2.91886666e+08  8.68750302e+09  8.68750303e+09  1.37735571e+10
  8.68750304e+09  8.68750303e+09  8.68750302e+09  8.68750303e+09
  8.68750302e+09 -7.69950203e+09  8.68750303e+09 -3.16013146e+09
  8.68750302e+09 -1.46869160e+09  8.68750304e+09  8.68750304e+09
  8.68750304e+09  8.68750304e+09  8.68750303e+09  8.68750303e+09
  8.68750303e+09  2.13229235e+07  8.68750303e+09  8.68750302e+09
  8.68750302e+09  8.68750301e+09  8.68750303e+09  8.68750303e+09
  8.68750303e+09  8.68750304e+09  8.68750300e+09  8.68750302e+09
  8.68750303e+09  8.68750303e+09  8.68750303e+09  8.68750304e+09
 -7.81723857e-02  8.68750303e+09  8.68750302e+09  9.68933105e-04
  8.68750302e+09  8.68750303e+09  8.68750302e+09  8.68750305e+09
  8.68750303e+09  8.68750302e+09  8.68750302e+09  8.68750304e+09
  8.68750302e+09  8.68750303e+09  8.68750303e+09  1.54009649e-06
  5.58212423e-06  1.92322511e-06  3.49636356e-06 -3.15198295e-06
  5.14889923e-06  6.61483627e-06  8.68750303e+09  8.68750304e+09
  8.68750301e+09  8.68750302e+09 -1.80612804e-07  8.68750303e+09
  8.68750303e+09  8.68750304e+09  8.68750304e+09  8.68750301e+09
  8.68750302e+09  8.68750303e+09  8.68750304e+09 -2.06365923e-06
  8.68750301e+09  8.68750303e+09  8.68750304e+09  8.68750302e+09
  8.68750303e+09  1.50380330e-09  8.68750303e+09  8.68750303e+09
  8.68750303e+09 -1.91717808e-10 -3.21520588e-13  8.68750303e+09
 -5.29136739e-14  8.68750304e+09  8.68750302e+09  8.68750303e+09
  8.68750301e+09 -9.19401816e-14  8.68750301e+09  8.68750304e+09
  8.68750304e+09  8.68750303e+09  8.68750303e+09  8.68750301e+09
  8.68750303e+09 -1.59872116e-13  2.26485497e-14  8.68750302e+09
  4.61852778e-14  5.81756865e-14  8.68750303e+09  8.68750302e+09
  8.68750304e+09  8.68750304e+09  8.68750301e+09  8.68750303e+09
  8.68750303e+09 -1.97918464e-13  8.68750303e+09 -1.82076576e-13
  8.68750304e+09  8.68750301e+09 -1.46830383e-13  8.68750304e+09
  8.68750303e+09  8.68750301e+09  8.68750302e+09  8.68750304e+09
  8.68750304e+09  8.68750299e+09  8.68750305e+09  8.68750305e+09
  8.68750302e+09  8.68750303e+09  8.68750302e+09  8.68750303e+09
 -6.08402217e-14  8.68750305e+09  8.68750302e+09  8.68750304e+09
  8.68750303e+09  8.68750303e+09  8.68750304e+09  8.68750304e+09
  8.68750302e+09  8.68750304e+09  8.68750303e+09  8.68750303e+09
  8.68750301e+09  8.68750303e+09  8.68750303e+09  1.01252340e-13
 -6.57252031e-14  8.68750304e+09  8.68750304e+09  8.68750305e+09
  8.68750303e+09  8.68750303e+09  8.68750302e+09  8.68750304e+09
 -9.76996262e-15  8.68750303e+09  8.68750304e+09  8.68750301e+09
  1.77635684e-15  8.68750304e+09  8.68750299e+09  8.68750303e+09
  8.68750302e+09  8.68750303e+09  8.68750303e+09  8.68750302e+09
  0.00000000e+00  8.68750304e+09  8.68750303e+09  8.68750302e+09
  8.68750303e+09  8.68750303e+09  8.68750303e+09  8.68750301e+09
  8.68750304e+09  0.00000000e+00  0.00000000e+00  8.68750303e+09
  8.68750305e+09  1.33226763e-15  8.68750304e+09  8.68750301e+09
  8.68750302e+09  8.68750304e+09  8.68750303e+09 -1.77635684e-15
  8.68750304e+09  0.00000000e+00  8.68750300e+09  8.68750303e+09
  8.68750303e+09  8.68750302e+09  8.68750303e+09  8.68750304e+09
  8.68750306e+09  8.68750302e+09  8.68750304e+09  8.68750303e+09
  8.68750304e+09  8.68750301e+09  8.68750303e+09  8.68750302e+09
  0.00000000e+00  8.68750304e+09  8.68750304e+09  8.68750304e+09
  8.68750301e+09  8.68750300e+09  8.68750301e+09  8.68750302e+09
  8.68750305e+09  0.00000000e+00  0.00000000e+00  8.68750301e+09
  8.68750301e+09  0.00000000e+00  8.68750302e+09]

In [18]:
ypred = regressor.predict(Xtest)

In [19]:
df4 = pd.DataFrame({'Actual': ytest.flatten(), 'Predicted': ypred.flatten()})
df4

      Actual  Predicted
0       91.0  73.508476
1       65.0  50.117462
2       70.0  74.740990
3       79.0  71.647465
4       69.0  69.100319
...      ...        ...
4148    72.0  76.977600
4149    61.0  77.548820
4150    82.0  77.821762
4151    70.0  71.965454
4152    56.0  54.815826

[4153 rows x 2 columns]